<a href="https://colab.research.google.com/github/keshavsikhwal/ASSIGNMENT-SUBMISSION/blob/main/probability_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###ASSIGNMENT 0 (CE605)
NAME : KESHAV SIKHWAL

 ROLLNO : 231030028

In [ ]:
#que_1 row vector by input method
import numpy as np #to import numpy libraray

input_for_row = input("enter element : ")#to take row element

a = np.array([float(element) for element in input_for_row.split()]) #to split the stinge into substringe and make an array in numpy

print("row vector",a)# to take print as row vector


enter element : 5 2.3 6 1.3 4
row vector [5.  2.3 6.  1.3 4. ]


In [ ]:
#que_1 coloumn vector by input method
input_for_coloumn = input("enter coloumn element: ") #inputting element for coloumn vector
a = np.array([float(x) for x in input_for_coloumn.split() ]).reshape(-1,1) #split list and making a sublist to store as array in numpy by using reshape and giving values in coloumn
print("coloumn vector",a )# to print coloumn



enter coloumn element: 4 2.3 1.5 8 7 0
coloumn vector [[4. ]
 [2.3]
 [1.5]
 [8. ]
 [7. ]
 [0. ]]


In [ ]:
#que_1 row vector by manual method
a = np.array([2,3,4,2.3]) #making a row  vector element
print("row vector", a) # to take print as row vector

row vector [2.  3.  4.  2.3]


In [ ]:
# ques_1 coloumn vector by manual method
a = np.array([[2],[3],[5.2],[8.6]])
print("coloumn vector",a)

coloumn vector [[2. ]
 [3. ]
 [5.2]
 [8.6]]


In [ ]:
#que_2 making a matrix by input method
import numpy as np
a = np.empty((5,5), dtype = float) #making empty matrix of 5*5
for i in range(5):#for loop to make 5 rows
    for j in range (5): # for loop to make 5 coloumns # for loop to make 5 coloumns
        element = float(input(f" enter row{i+1}, enter coloumn{j+1} "))# to take element for row and coloumn
        a[i,j] = element # to store element in empty matrix
print("matrix",a)      #to print a as matrix


 enter row1, enter coloumn1 1
 enter row1, enter coloumn2 2.3
 enter row1, enter coloumn3 4
 enter row1, enter coloumn4 .3
 enter row1, enter coloumn5 8.3
 enter row2, enter coloumn1 8
 enter row2, enter coloumn2 4
 enter row2, enter coloumn3 0
 enter row2, enter coloumn4 0
 enter row2, enter coloumn5 6
 enter row3, enter coloumn1 4
 enter row3, enter coloumn2 5
 enter row3, enter coloumn3 1
 enter row3, enter coloumn4 5
 enter row3, enter coloumn5 20
 enter row4, enter coloumn1 0
 enter row4, enter coloumn2 7
 enter row4, enter coloumn3 4
 enter row4, enter coloumn4 9
 enter row4, enter coloumn5 7
 enter row5, enter coloumn1 2
 enter row5, enter coloumn2 0
 enter row5, enter coloumn3 0
 enter row5, enter coloumn4 0
 enter row5, enter coloumn5 3
matrix [[ 1.   2.3  4.   0.3  8.3]
 [ 8.   4.   0.   0.   6. ]
 [ 4.   5.   1.   5.  20. ]
 [ 0.   7.   4.   9.   7. ]
 [ 2.   0.   0.   0.   3. ]]


In [ ]:
# que_2 making a matrix by manual method
a = np.array( [[ 1,   2.3,  4,   0.3,  8.3], # insert a matrix
 [ 8,   4,   0,   0,   6. ],
 [ 4,   5,   1,   5,  20. ],
 [ 0,   7,   4 ,  9,   7. ],
 [ 2,   0,   0,  0,   3. ]])
print("manual matrix",a) # print a as maual matrix

manual matrix [[ 1.   2.3  4.   0.3  8.3]
 [ 8.   4.   0.   0.   6. ]
 [ 4.   5.   1.   5.  20. ]
 [ 0.   7.   4.   9.   7. ]
 [ 2.   0.   0.   0.   3. ]]


In [ ]:
#que_3 getting third row of the matrix
a = np.array( [[ 1,   2.3,  4,   0.3,  8.3],  #to insert matrix in numpy
 [ 8,   4,   0,   0,   6. ],
 [ 4,   5,   1,   5,  20. ],
 [ 0,   7,   4 ,  9,   7. ],
 [ 2,   0,   0,  0,   3. ]])
third_row = a[2] #to take third row the index number will be 2
print(third_row)





[ 4.  5.  1.  5. 20.]


In [ ]:
#que_4 getting forth coloumn of matrix a
forth_coloumn = a[:,3]
print(forth_coloumn)


[0.3 0.  5.  9.  0. ]


In [ ]:
#que_5 sorting matrix row wise
row_sorted = np.sort(a,axis=1)
print(row_sorted)

[[ 0.3  1.   2.3  4.   8.3]
 [ 0.   0.   4.   6.   8. ]
 [ 1.   4.   5.   5.  20. ]
 [ 0.   4.   7.   7.   9. ]
 [ 0.   0.   0.   2.   3. ]]


In [ ]:
#que_5 sorting coloumns
coloumn_sorted = np.sort(a,axis=0)#to sort  matrix we used .sort function
print(coloumn_sorted) #to take print as coloumn_sorted

[[ 0.   0.   0.   0.   3. ]
 [ 1.   2.3  0.   0.   6. ]
 [ 2.   4.   1.   0.3  7. ]
 [ 4.   5.   4.   5.   8.3]
 [ 8.   7.   4.   9.  20. ]]


In [ ]:
#que_6 making a matrix to multiply elements with 10 if its greater than 2
a = np.array( [[ 1,   2.3,  4,   0.3,  8.3],  #to insert matrix in numpy
 [ 8,   4,   0,   0,   6. ],
 [ 4,   5,   1,   5,  20. ],
 [ 0,   7,   4 ,  9,   7. ],
 [ 2,   0,   0,  0,   3. ]])
b = np.copy(a)# making a same copy as a to take same values and use for loop in it
for i in range(5):# for loop for row element
  for j in range(5):# for loop for coloumn element
    if b[i,j] > 2:#making condition
      b[i,j] *= 10
print("matrix b ",b)#to take print of matrix b


matrix b  [[  1.   23.   40.    0.3  83. ]
 [ 80.   40.    0.    0.   60. ]
 [ 40.   50.    1.   50.  200. ]
 [  0.   70.   40.   90.   70. ]
 [  2.    0.    0.    0.   30. ]]


In [ ]:
#que_7 adding matrix a and matrix b
a = np.array( [[ 1,   2.3,  4,   0.3,  8.3],
 [ 8,   4,   0,   0,   6. ],
 [ 4,   5,   1,   5,  20. ],
 [ 0,   7,   4 ,  9,   7. ],
 [ 2,   0,   0,  0,   3. ]])
b = np.array([[  1.,   23.,   40.,    0.3,  83. ],
 [ 80. ,  40. ,   0. ,   0. ,  60. ],
 [ 40.,   50. ,   1. ,  50.,  200. ],
 [  0.,   70.,   40. ,  90. ,  70. ],
 [  2.,    0. ,   0.,    0,   30. ]])
c = a + b# using simple '+' operator
print("sum of matrices ",c)#to print of c as sum of matrices


sum of matrices  [[  2.   25.3  44.    0.6  91.3]
 [ 88.   44.    0.    0.   66. ]
 [ 44.   55.    2.   55.  220. ]
 [  0.   77.   44.   99.   77. ]
 [  4.    0.    0.    0.   33. ]]


In [ ]:
#ques_8 to sbtract matrix b from a
a = np.array( [[ 1,   2.3,  4,   0.3,  8.3],
 [ 8,   4,   0,   0,   6. ],
 [ 4,   5,   1,   5,  20. ],
 [ 0,   7,   4 ,  9,   7. ],
 [ 2,   0,   0,  0,   3. ]])
b = np.array([[  1.,   23.,   40.,    0.3,  83. ],
 [ 80. ,  40. ,   0. ,   0. ,  60. ],
 [ 40.,   50. ,   1. ,  50.,  200. ],
 [  0.,   70.,   40. ,  90. ,  70. ],
 [  2.,    0. ,   0.,    0,   30. ]])
d = a - b #subtract matrix using '-' operator
print("subtraction of matrices ", d)


subtraction of matrices  [[   0.   -20.7  -36.     0.   -74.7]
 [ -72.   -36.     0.     0.   -54. ]
 [ -36.   -45.     0.   -45.  -180. ]
 [   0.   -63.   -36.   -81.   -63. ]
 [   0.     0.     0.     0.   -27. ]]


In [ ]:
#ques_9 multiplication element wise
a = np.array( [[ 1,   2.3,  4,   0.3,  8.3],
 [ 8,   4,   0,   0,   6. ],
 [ 4,   5,   1,   5,  20. ],
 [ 0,   7,   4 ,  9,   7. ],
 [ 2,   0,   0,  0,   3. ]])
b = np.array([[  1.,   23.,   40.,    0.3,  83. ],
 [ 80. ,  40. ,   0. ,   0. ,  60. ],
 [ 40.,   50. ,   1. ,  50.,  200. ],
 [  0.,   70.,   40. ,  90. ,  70. ],
 [  2.,    0. ,   0.,    0,   30. ]])
M = a * b # multiplication by using '*' operator
print("multiplication element wise",M) # print M as multiplication element wise


multiplication element wise [[1.000e+00 5.290e+01 1.600e+02 9.000e-02 6.889e+02]
 [6.400e+02 1.600e+02 0.000e+00 0.000e+00 3.600e+02]
 [1.600e+02 2.500e+02 1.000e+00 2.500e+02 4.000e+03]
 [0.000e+00 4.900e+02 1.600e+02 8.100e+02 4.900e+02]
 [4.000e+00 0.000e+00 0.000e+00 0.000e+00 9.000e+01]]


In [ ]:
# ques_9 matrix multiplication
a = np.array( [[ 1,   2.3,  4,   0.3,  8.3],
 [ 8,   4,   0,   0,   6. ],
 [ 4,   5,   1,   5,  20. ],
 [ 0,   7,   4 ,  9,   7. ],
 [ 2,   0,   0,  0,   3. ]])
b = np.array([[  1.,   23.,   40.,    0.3,  83. ],
 [ 80. ,  40. ,   0. ,   0. ,  60. ],
 [ 40.,   50. ,   1. ,  50.,  200. ],
 [  0.,   70.,   40. ,  90. ,  70. ],
 [  2.,    0. ,   0.,    0,   30. ]])
m = np.dot(a,b) # to do matrix multiplication
print("matrix multiplication ", m) # to print m as matrix multiplication


matrix multiplication  [[3.616e+02 3.360e+02 5.600e+01 2.273e+02 1.291e+03]
 [3.400e+02 3.440e+02 3.200e+02 2.400e+00 1.084e+03]
 [4.840e+02 6.920e+02 3.610e+02 5.012e+02 1.782e+03]
 [7.340e+02 1.110e+03 3.640e+02 1.010e+03 2.060e+03]
 [8.000e+00 4.600e+01 8.000e+01 6.000e-01 2.560e+02]]


In [ ]:
#ques_10 multilpication of each matrix by 18
a = np.array( [[ 1,   2.3,  4,   0.3,  8.3],
 [ 8,   4,   0,   0,   6. ],
 [ 4,   5,   1,   5,  20. ],
 [ 0,   7,   4 ,  9,   7. ],
 [ 2,   0,   0,  0,   3. ]])
b = np.array([[  1.,   23.,   40.,    0.3,  83. ],
 [ 80. ,  40. ,   0. ,   0. ,  60. ],
 [ 40.,   50. ,   1. ,  50.,  200. ],
 [  0.,   70.,   40. ,  90. ,  70. ],
 [  2.,    0. ,   0.,    0,   30. ]])
f = a/18 # to divide each element by 18
g = b/18 # to divide each element by 18
print("result for a ",f) # to print f as result for a
print("result for b ",g) # to print g as result for b

result for a  [[0.05555556 0.12777778 0.22222222 0.01666667 0.46111111]
 [0.44444444 0.22222222 0.         0.         0.33333333]
 [0.22222222 0.27777778 0.05555556 0.27777778 1.11111111]
 [0.         0.38888889 0.22222222 0.5        0.38888889]
 [0.11111111 0.         0.         0.         0.16666667]]
result for b  [[ 0.05555556  1.27777778  2.22222222  0.01666667  4.61111111]
 [ 4.44444444  2.22222222  0.          0.          3.33333333]
 [ 2.22222222  2.77777778  0.05555556  2.77777778 11.11111111]
 [ 0.          3.88888889  2.22222222  5.          3.88888889]
 [ 0.11111111  0.          0.          0.          1.66666667]]


In [ ]:
#ques_11 finding inverse of matrix
a = np.array( [[ 1,   2.3,  4,   0.3,  8.3],# saving matrices in numpy array
 [ 8,   4,   0,   0,   6. ],
 [ 4,   5,   1,   5,  20. ],
 [ 0,   7,   4 ,  9,   7. ],
 [ 2,   0,   0,  0,   3. ]])
b = np.array([[  1.,   23.,   40.,    0.3,  83. ],
 [ 80. ,  40. ,   0. ,   0. ,  60. ],
 [ 40.,   50. ,   1. ,  50.,  200. ],
 [  0.,   70.,   40. ,  90. ,  70. ],
 [  2.,    0. ,   0.,    0,   30. ]])
c = np.linalg.inv(a) # using linear algebra (linalg) function in which using inverse function
d = np.linalg.inv(b)
print("inverse of a ",c)#to take desirable  print
print("inverse of b",d)

inverse of a  [[-0.03196435  0.0446048  -0.1011236   0.05724525  0.53981015]
 [ 0.03196435  0.2053952   0.1011236  -0.05724525 -1.03981015]
 [ 0.20534676 -0.05927935 -0.16853933  0.08678807  0.47152267]
 [-0.1327005  -0.11027702 -0.05617978  0.14674545  0.6198179 ]
 [ 0.02130957 -0.02973654  0.06741573 -0.0381635  -0.0265401 ]]
inverse of b [[-0.03079968  0.03360189 -0.05785825  0.03224614  0.32848933]
 [ 0.05851939 -0.03884358  0.10993067 -0.06126766 -0.67412972]
 [-0.01182536  0.02599025 -0.06933475  0.03855873  0.35299765]
 [-0.04185639  0.02040277 -0.05768624  0.04329854  0.35854213]
 [ 0.00205331 -0.00224013  0.00385722 -0.00214974  0.01143404]]


In [ ]:
#ques_11 finding matrix rank
r_a = np.linalg.matrix_rank(a) #using linalg function and matrix_rank function to find rank of matrix
r_b = np.linalg.matrix_rank(b)
print("rank of matrix a",r_a) # to print r_a as rank of matrix
print("rank of matrix b", r_b)  # to print r_b as rank of matrix

rank of matrix a 5
rank of matrix b 5


In [ ]:
# que_11  finding condition number

a = np.array( [[ 1,   2.3,  4,   0.3,  8.3],# saving matrices in numpy array
 [ 8,   4,   0,   0,   6. ],
 [ 4,   5,   1,   5,  20. ],
 [ 0,   7,   4 ,  9,   7. ],
 [ 2,   0,   0,  0,   3. ]])
b = np.array([[  1.,   23.,   40.,    0.3,  83. ],
 [ 80. ,  40. ,   0. ,   0. ,  60. ],
 [ 40.,   50. ,   1. ,  50.,  200. ],
 [  0.,   70.,   40. ,  90. ,  70. ],
 [  2.,    0. ,   0.,    0,   30. ]])
c = np.linalg.cond(a) # to find condition number we used .cond function
d = np.linalg.cond(b)
print("condition number for a ", c)# to take print as desirable
print("condition number for b ", d)

n_a = np.linalg.norm(a, ord='fro') # to find norm of a and b we used .norm function
n_b = np.linalg.norm(b, ord='fro')
print("norm of a ", n_a)
print("norm of b ", n_b)


condition number for a  39.29189746914045
condition number for b  249.79004886538308
norm of a  29.703030148454552
norm of b  296.0136652251041


In [ ]:
#ques_12 to find  inner product and outer product of coloumn vector
import numpy as np
a = np.array([[2], [3], [5.2], [8.6]]) # to store coloumn vector in numpy array

inner_product = np.inner(a, a) # to calculate inner product we used .inner function

outer_product = np.outer(a, a)# to calculate outer product we used .outer product
print("inner Product:",inner_product)
print("outer product",outer_product)



inner Product: [[ 4.    6.   10.4  17.2 ]
 [ 6.    9.   15.6  25.8 ]
 [10.4  15.6  27.04 44.72]
 [17.2  25.8  44.72 73.96]]
outer product [[ 4.    6.   10.4  17.2 ]
 [ 6.    9.   15.6  25.8 ]
 [10.4  15.6  27.04 44.72]
 [17.2  25.8  44.72 73.96]]


In [ ]:
# que_13  to write a function called derivative which takes input parameters f(x), b, method (forward,backward and central)
import math # to import different mathematical operation
def derivative(f, b, method='central', h=0.01):
    if method == 'forward':# making a condition for forward return
        return (f(b + h) - f(b)) / h
    elif method == 'backward':# making a condion for backward return
        return (f(b) - f(b - h)) / h
    elif method == 'central': # making a condition for central return
        return (f(b + h) - f(b - h)) / (2 * h)
    else:
        raise ValueError("Invalid method. Use 'forward', 'backward', or 'central'.")

# Test the function with e^x and cos(x) at x = 0.5
x = 0.5


def exp_x(x):
    return math.exp(x)

def cos_x(x):
    return math.cos(x)

forward_derivative_exp  =  derivative(exp_x, x, method='forward') # Calculating  derivatives using forward  methods
backward_derivative_exp=  derivative(exp_x, x, method='backward') # calculating derivatives using backward method
central_derivative_exp=  derivative(exp_x, x) # calculating derivative using central method

forward_derivative_cos = derivative(cos_x, x, method='forward')
backward_derivative_cos = derivative(cos_x, x, method='backward')
central_derivative_cos = derivative(cos_x, x)


# Print the results
print("Derivative of e^x at x = 0.5:")
print("Forward Difference:", forward_derivative_exp)
print("Backward Difference:", backward_derivative_exp)
print("Central Difference:", central_derivative_exp)
print()

print("Derivative of cos(x) at x = 0.5:")
print("Forward Difference:", forward_derivative_cos)
print("Backward Difference:", backward_derivative_cos)
print("Central Difference:", central_derivative_cos)


Derivative of e^x at x = 0.5:
Forward Difference: 1.6569924245758205
Backward Difference: 1.6405050744749294
Central Difference: 1.648748749525375

Derivative of cos(x) at x = 0.5:
Forward Difference: -0.483805424462147
Backward Difference: -0.4750296719748692
Central Difference: -0.4794175482185081


In [ ]:
# que_14 to read aws data in google colab
from google.colab import drive # to connect drive with google colab

drive.mount('/content/drive')



Mounted at /content/drive


In [ ]:
#que_14.....
from google.colab import files #to upload file in google drive so that path can be taken and file can be read by google colab

uploaded = files.upload()


Saving aws data.csv to aws data.csv


In [ ]:
import pandas as pd #importing panda

path = '/content/drive/MyDrive/Colab Notebooks/aws data.csv' # it is the path which is copied from drive
data = pd.read_csv(path) #to read .csv file


In [ ]:
print(data) # to take print of data

                    created_at  entry_id  Soil Temperature  Soil Moisture  \
0    2022-12-14T14:19:11+05:30     10830             21.06            817   
1    2022-12-14T14:20:13+05:30     10831             21.06            817   
2    2022-12-14T14:21:15+05:30     10832             21.06            817   
3    2022-12-14T14:22:18+05:30     10833             21.06            817   
4    2022-12-14T14:23:20+05:30     10834             21.06            817   
..                         ...       ...               ...            ...   
654  2022-12-26T14:37:18+05:30     11484             20.50            818   
655  2022-12-26T15:17:18+05:30     11485           4095.94            818   
656  2022-12-26T15:57:59+05:30     11486             20.50            818   
657  2022-12-26T16:58:03+05:30     11487             20.00            816   
658  2022-12-26T17:18:03+05:30     11488             19.75            816   

     Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage